# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
#' @rdname sqlParseVariables
#' @param sql SQL to parse (a character vector of length 1)
#' @param quotes A list of \code{QuoteSpec} calls defining the quoting
#'   specification.
#' @param comments A list of \code{CommentSpec} calls defining the commenting
#'   specification.
sqlParseVariablesImpl <- function(sql, quotes, comments) {
    .Call('DBI_sqlParseVariablesImpl', PACKAGE = 'DBI', sql, quotes, comments)
}

