name: 'Custom steps to run after R packages are installed'

runs:
  using: "composite"
  steps:
    # Must happen after installing system dependencies,
    # https://github.com/ankane/setup-mariadb/issues/2
    - uses: ankane/setup-mariadb@v1
      with:
        mariadb-version: "10.11"

    - name: Create database, set it to UTF-8
      run: |
        mysql -e "CREATE DATABASE IF NOT EXISTS test; ALTER DATABASE test CHARACTER SET 'utf8'; FLUSH PRIVILEGES;"
      shell: bash

    # Must happen after R is installed...
    - name: Define R CMD check error condition
      run: |
        if (getRversion() < "3.5" || (.Platform$OS.type == "windows" && getRversion() < "4.0")) {
          message("Setting RCMDCHECK_ERROR_ON")
          cat('RCMDCHECK_ERROR_ON="warning"\n', file = Sys.getenv("GITHUB_ENV"), append = TRUE)
        }
      shell: Rscript {0}
